// Package auth implements the IAM's core login use case (architecture
// plan §9): begin an SSO login, resolve the caller's Identity from the
// provider callback, and mint the IAM's own JWT. No Supabase type, and
// no HTTP type, appears anywhere in this package.
package auth

import (
	"context"
	"fmt"
	"time"

	"github.com/haribabuk113/iam/internal/application/ports/outbound"
	"github.com/haribabuk113/iam/internal/domain/identity"
	"github.com/haribabuk113/iam/internal/domain/provider"
)

type Service struct {
	authProvider outbound.AuthProviderPort
	identities   outbound.IdentityRepository
	tokens       outbound.TokenSigner
}

func NewService(authProvider outbound.AuthProviderPort, identities outbound.IdentityRepository, tokens outbound.TokenSigner) *Service {
	return &Service{authProvider: authProvider, identities: identities, tokens: tokens}
}

// BeginLogin returns the URL to redirect the browser to for the given
// provider. state and codeChallenge are generated by the caller (PKCE,
// CSRF binding) and stored against the in-flight login attempt.
func (s *Service) BeginLogin(p provider.Name, state, codeChallenge string) (string, error) {
	if !p.Valid() {
		return "", fmt.Errorf("auth: unsupported provider %q", p)
	}
	return s.authProvider.AuthorizeURL(p, state, codeChallenge)
}

// CompleteLogin exchanges the provider's callback code for a verified
// external identity, then resolves it to an IAM Identity — reusing an
// existing one on verified-email match (architecture plan §22, decision
// #1), linking the provider, or creating a new Identity.
func (s *Service) CompleteLogin(ctx context.Context, code, codeVerifier string) (identity.Identity, error) {
	ext, err := s.authProvider.ExchangeCode(ctx, code, codeVerifier)
	if err != nil {
		return identity.Identity{}, fmt.Errorf("auth: exchange code: %w", err)
	}
	return s.resolveIdentity(ctx, ext)
}

// SignUp registers a new email+password user with Supabase. sessionIssued
// is false when Supabase requires email confirmation (its default) — the
// returned Identity is the zero value in that case, and the caller must
// tell the user to confirm their email before signing in.
func (s *Service) SignUp(ctx context.Context, email, password, fullName string) (id identity.Identity, sessionIssued bool, err error) {
	ext, sessionIssued, err := s.authProvider.SignUpWithPassword(ctx, email, password, fullName)
	if err != nil {
		return identity.Identity{}, false, fmt.Errorf("auth: signup: %w", err)
	}
	if !sessionIssued {
		return identity.Identity{}, false, nil
	}
	id, err = s.resolveIdentity(ctx, ext)
	return id, true, err
}

// SignIn authenticates an existing email+password user.
func (s *Service) SignIn(ctx context.Context, email, password string) (identity.Identity, error) {
	ext, err := s.authProvider.SignInWithPassword(ctx, email, password)
	if err != nil {
		return identity.Identity{}, fmt.Errorf("auth: signin: %w", err)
	}
	return s.resolveIdentity(ctx, ext)
}

// resolveIdentity maps a verified ExternalIdentity (from any auth method —
// OAuth callback or password signup/signin) onto the IAM's own Identity:
// reusing an existing one on verified-email match (architecture plan §22,
// decision #1), linking the provider, or creating a new Identity.
func (s *Service) resolveIdentity(ctx context.Context, ext outbound.ExternalIdentity) (identity.Identity, error) {
	if existing, err := s.identities.FindByProviderUser(ctx, ext.Provider, ext.ProviderUserID); err != nil {
		return identity.Identity{}, fmt.Errorf("auth: lookup by provider user: %w", err)
	} else if existing != nil {
		return *existing, nil
	}

	// Auto-merge into an existing Identity only on a verified-email match —
	// an unverified email is never trusted to merge accounts.
	if ext.EmailVerified {
		existing, err := s.identities.FindByVerifiedEmail(ctx, ext.Email)
		if err != nil {
			return identity.Identity{}, fmt.Errorf("auth: lookup by email: %w", err)
		}
		if existing != nil {
			if err := s.identities.LinkProvider(ctx, existing.ID, ext.Provider, ext.ProviderUserID); err != nil {
				return identity.Identity{}, fmt.Errorf("auth: link provider: %w", err)
			}
			return *existing, nil
		}
	}

	newIdentity := identity.Identity{
		ID:              identity.NewClientEcosystemID(),
		FullName:        ext.FullName,
		Email:           ext.Email,
		PrimaryProvider: string(ext.Provider),
		Status:          identity.StatusActive,
		CreatedAt:       time.Now(),
	}
	if err := s.identities.Create(ctx, newIdentity); err != nil {
		return identity.Identity{}, fmt.Errorf("auth: create identity: %w", err)
	}
	if err := s.identities.LinkProvider(ctx, newIdentity.ID, ext.Provider, ext.ProviderUserID); err != nil {
		return identity.Identity{}, fmt.Errorf("auth: link provider: %w", err)
	}
	return newIdentity, nil
}

// IssueToken mints the IAM's own JWT for an already-resolved Identity.
func (s *Service) IssueToken(id identity.Identity) (token string, expiresAt time.Time, err error) {
	return s.tokens.Sign(outbound.IdentityClaims{
		EcosystemID: string(id.ID),
		Email:       id.Email,
		FullName:    id.FullName,
		Status:      string(id.Status),
	})
}

// IdentityByID re-loads an Identity by its ecosystem ID — used by the
// token-exchange endpoint after the browser hands back the opaque
// exchange code (architecture plan §9).
func (s *Service) IdentityByID(ctx context.Context, id identity.ClientEcosystemID) (*identity.Identity, error) {
	return s.identities.FindByID(ctx, id)
}
