package outbound

import (
	"context"

	"github.com/company/iam/internal/domain/provider"
)

// ExternalIdentity is the normalized shape every provider adapter must
// produce — no provider-specific field ever leaks past this type.
type ExternalIdentity struct {
	Provider       provider.Name
	ProviderUserID string
	Email          string
	FullName       string
	EmailVerified  bool
}

// AuthProviderPort is the single seam through which the IAM talks to an
// external SSO backend. Today the only implementation is the Supabase
// adapter (internal/adapters/outbound/supabase). No Supabase type may
// appear on either side of this interface — that's what makes Supabase
// replaceable later without touching any use case or handler.
type AuthProviderPort interface {
	// AuthorizeURL returns the URL to redirect the browser to in order to
	// start the OAuth dance for the given provider. state and
	// codeChallenge are generated by the caller (PKCE, CSRF binding).
	AuthorizeURL(p provider.Name, state, codeChallenge string) (string, error)

	// ExchangeCode trades an authorization code + PKCE verifier for a
	// verified external identity.
	ExchangeCode(ctx context.Context, code, codeVerifier string) (ExternalIdentity, error)
}
